stages:
  - lint
  - test

variables:
  PYTHON_VERSION: "3.12"
  UV_VERSION: "0.11.3"

default:
  image: ghcr.io/astral-sh/uv:python${PYTHON_VERSION}-trixie-slim

ruff:
  stage: lint
  needs: [ ]
  script:
    - uv run ruff check .

mypy:
  stage: lint
  needs: [ ]
  script:
    - uv run mypy .

test:
  stage: test
  parallel:
    matrix:
      - PYTHON_VERSION: [ "3.12", "3.13", "3.14" ]
  needs:
    - ruff
    - mypy
  script:
    - uv run pytest
